### PR TITLE
Compile on CPU  by default if no CUDA device

### PR DESCRIPTION
**Pull request by nicolas-chaulet**
Hi,
It would be nice to have cpu only mode by default when the platform does not have a CUDA device, this PR introduces the change.
Let me know if you'd like me to amend the doc, I think it is ok as it is.
Best,
Nicolas

### CODE REVIEW

**Comment by chrischoy** [comment]
Thanks for the PR

**Comment by nicolas-chaulet** [comment]
Thank you for the great work! Any chance you could make a release? How do you manage your CI and CD?

**Comment by chrischoy** [comment]
Currently working on CI, but might take some time.

It seems that people simply install on server head nodes without GPU and use it on nodes with GPU.

https://github.com/chrischoy/FCGF/issues/24

https://github.com/StanfordVL/MinkowskiEngine/issues/113

It seems that users are unaware of CPU_ONLY installation and might be better for them to fail during installation rather than fail during runtime.

**Comment by nicolas-chaulet** [comment]
Humm that's interesting... Maybe the way we detect GPUs is wrong? 

> It seems that people simply install on server head nodes without GPU and use it on nodes with GPU.

I am not sure it's about that, if it were that then pytorch would be the CPU version as well no?

Regarding CI, we have used github actions recently and it is quite straightforward, happy to give you a hand if you like. Not sure if they support CUDA code though

**Comment by chrischoy** [comment]
At our school, we use SLURM for job scheduling and the head node, which we use to submit jobs, does not have a GPU nor nvcc. So, we have to access slave nodes interactively to compile a CUDA program.

Or another way would be giving out warnings to users if it tries to use GPU function at runtime.

Sure, any help on CI would be appreciated.

**Pull request merged**
